# Buildpack API version
# api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "com.starkandwayne.buildpacks.redis"
version = "1.0.0"
name = "Redis Buildpack"

[[metadata.dependencies]]
id = "redis"
name = "Redis"
version = "5.0.5"
major_version = "5"
source = "http://download.redis.io/releases/redis-5.0.5.tar.gz"
source_sha256 = "2139009799d21d8ff94fc40b7f36ac46699b9e1254086299f8d3b223ca54a375"

[[metadata.dependencies]]
id = "redis"
name = "Redis"
version = "4.0.14"
major_version = "4"
source = "http://download.redis.io/releases/redis-4.0.14.tar.gz"
source_sha256 = "1e1e18420a86cfb285933123b04a82e1ebda20bfb0a289472745a087587e93a7"

# Stacks that the buildpack will work with (requires yj + jq)
[[stacks]]
id = "io.buildpacks.stacks.bionic"

# Fails due to missing yj
# [[stacks]]
# id = "org.cloudfoundry.stacks.cflinuxfs3"

# Fails due to missing yj + jq
# [[stacks]]
# id = "heroku-18"

